example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('wishlist/ajax', include('wishlist.urls')),


    
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_wishlist_ajax
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('wishlist/ajax', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Kenneth Ferdinand',
    'last_login': request.COOKIES['last_login'],
}
    return render(request, "wishlist.html", context)


@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
    'nama': 'Kenneth Ferdinand',
    'last_login': request.COOKIES['last_login'],
}
    return render(request, "wishlist_ajax.html", context)

def show_json_by_id(request, id) :
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id) :
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response


data_barang_wishlist = BarangWishlist.objects.all()
context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Kenneth'
    }

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
<!DOCTYPE html>
<title>Login</title>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <h1 style="font-family:monospace">Login</h1>
</head>
<body>

    <div class = "login">
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td style="font-family:monospace;font-size: large;">Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td style="font-family:monospace;font-size: large;">Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>
    
                <tr>
                    <td></td>
                    <td><input style="font-family:monospace;font-size: large;"" class="btn login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>
    
        {% if messages %}
            <ul >
                {% for message in messages %}
                    <li style="font-family:monospace;font-size: large;">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Belum mempunyai akun? <a style="font-family:monospace;font-size: large;"" href="{% url 'wishlist:register' %}">Buat Akun</a>
    
    </div>
</body>

</html>

wishlist/templates/register.html
<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <title>Registrasi Akun</title>
    </head>
    
    <body>
        <div class = "login">
            
            <h1 style="font-family:monospace;justify-content: center;font-size: larger;">Formulir Registrasi</h1>  
        
                <form method="POST" >  
                    {% csrf_token %}  
                    <table style="font-family:monospace;font-size: large;color:cadetblue">  
                        {{ form.as_table }}  
                        <tr>  
                            <td></td>
                            <td ><input type="submit" name="submit" value="Daftar"/></td>  
                        </tr>  
                    </table>  
                </form>
        
            {% if messages %}  
                <ul >   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                        {% endfor %}  
                </ul>   
            {% endif %}
        
        </div>  
    </body>
    
    
    
</html>

wishlist/templates/wishlist.html
<!doctype html>
<html lang="en">

    <nav class="navbar navbar-expand-lg bg-light" >
        <div class="container-fluid"style="background-color: #a7bed3;">
          <a style="font-family: monospace;font-size: large;"class="navbar-brand" href="#">Kenneth Ferdinand</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown" >
            <ul class="navbar-nav">
              <li class="nav-item"style="background-color: blue;">
                <button ><a href="{% url 'wishlist:logout' %}">Logout</a></button>
              </li>
            </ul>
          </div>
        </div>
      </nav>

     

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <h6 style="color: blue; margin: auto;margin-left:1%;font-family: monospace;font-size: large;">Nama: </h6>
    <p style="color: red;margin: auto;font-size: small;margin-left:1%;font-family: monospace;font-size: large;">{{nama}}</p>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <table style="color: grey ;margin-left:1%;font-family: monospace;" class="table table-striped">
        <tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
        </tr>
    {% for barang in list_barang %}
    <tr style="color: black;">
        <th>{{barang.nama_barang}}</th>
        <th>{{barang.harga_barang}}</th>
        <th >{{barang.deskripsi}}</th>
    </tr>
    {% endfor %}
    </table>
    <h5 style="font-size:small;margin-top:32%;font-family: monospace;">Sesi terakhir login: {{ last_login }}</h5>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>


</html>

wishlist/templates/wishlist_ajax.html
<!doctype html>
<html lang="en">

<script>
  $(document).ready(function () {
    $.get("{% url 'wishlist:show_json' %}", function (data) {
      $.each(data, function(index, value) {
        $("#wishlist-table").append (
          "<tr><td>" + 
            value.fields.nama_barang + 
            "</td><td>" + 
              value.fields.harga_barang + 
              "</td><td>" + 
                value.fields.deskripsi +
                "</td></tr>"
        )
      })
    })
  })
</script>

    <nav class="navbar navbar-expand-lg bg-light" >
        <div class="container-fluid"style="background-color: #a7bed3;">
          <a style="font-family: monospace;font-size: large;"class="navbar-brand" href="#">Kenneth Ferdinand</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown" >
            <ul class="navbar-nav">
              <li class="nav-item"style="background-color: blue;">
                <button ><a href="{% url 'wishlist:logout' %}">Logout</a></button>
              </li>
            </ul>
          </div>
        </div>
      </nav>

     

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <h6 style="color: blue; margin: auto;margin-left:1%;font-family: monospace;font-size: large;">Nama: </h6>
    <p style="color: red;margin: auto;font-size: small;margin-left:1%;font-family: monospace;font-size: large;">{{nama}}</p>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <table id = "wishlist-table" style="color: grey ;margin-left:1%;font-family: monospace;" class="table table-striped">
        <tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
        </tr>
    </table>
    <h5 style="font-size:small;margin-top:32%;font-family: monospace;">Sesi terakhir login: {{ last_login }}</h5>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>


</html>